# Generated by Django 3.1.4 on 2020-12-08 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя врача'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.doctors', verbose_name='Имя врача'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='patient',
            field=models.CharField(max_length=255, verbose_name='Имя пациента'),
        ),
    ]
