# Generated by Django 3.1.4 on 2020-12-08 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20201208_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='data',
            new_name='date',
        ),
    ]
